image: ruby:2.5

cache:
  paths:
  - vendor/

before_script:
  - bundle install -j $(nproc) --path vendor

test:
  stage: test
  script:
    - bundle exec rake test

rubocop:
  stage: test
  script:
    - bundle exec rubocop
